from pathlib import Path

from run import load_params_yaml, simulate_no_meal, simulate_peak_deltaG


def test_steady_state_no_meal():
    """Verifies that the system remains in steady state when no meal is consumed.

    This test checks if the glucose and insulin levels remain close to their basal values
    (Gb and Ib) over a period of time when there is no external input.

    Note:
        Documentation generated by Jules (Google AI).
    """
    params = load_params_yaml()
    G, I = simulate_no_meal(params, t_end_min=120.0, dt_min=0.5)
    assert abs(G[-1] - params["Gb_mg_dL"]) < 0.5
    assert abs(I[-1] - params["Ib_uU_mL"]) < 0.5


def test_dt_halving_peak_deltaG():
    """Verifies numerical stability by checking convergence with smaller time steps.

    This test compares the peak glucose change obtained with a standard time step
    against one obtained with half that time step. The relative difference should be small.

    Note:
        Documentation generated by Jules (Google AI).
    """
    params = load_params_yaml()
    fp = sorted(Path("configs/frozen").glob("*.yaml"))[0]
    peak1 = simulate_peak_deltaG(params, fp, dt_min=0.5)
    peak2 = simulate_peak_deltaG(params, fp, dt_min=0.25)
    rel = abs(peak2 - peak1) / max(1e-6, abs(peak1))
    assert rel < 0.01
