"""ctypes bindings for the Bergman minimal model RK4 core."""
from __future__ import annotations # For Python 3.7 compatibility and forward references in type hints

import ctypes
import hashlib
import os
import platform
import subprocess
import sys
from ctypes import POINTER, Structure, c_double
from pathlib import Path
from typing import Dict, Optional

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
BUILD_DIR = ROOT / "build"

BUILD_METADATA: Dict[str, object] = {}


def _shared_name() -> str:
    if sys.platform.startswith("win"): #windows, obviously
        return "model.dll"
    if sys.platform == "darwin": #macOS, (darwin = unix based OS)
        return "libmodel.dylib"
    return "libmodel.so" #linux


def _candidate_commands(output: Path) -> list[list[str]]:
    src = str(SRC_DIR / "model.c")

    # Use MSVC-style /I only for cl; use -I for gcc/clang
    include_msvc = f"/I{SRC_DIR}"
    include_posix = f"-I{SRC_DIR}"

    if sys.platform.startswith("win"):
        return [
            [
                "cl",
                "/nologo",
                "/LD",
                "/DBUILDING_MODEL",
                include_msvc,
                src,
                f"/Fe{output}",
            ],
            [
                "gcc",
                "-O3",
                "-shared",
                "-fPIC",
                "-DBUILDING_MODEL",
                include_posix,
                src,
                "-o",
                str(output),
            ],
        ]

    if sys.platform == "darwin":
        return [
            [
                "clang",
                "-O3",
                "-dynamiclib",
                "-fPIC",
                "-DBUILDING_MODEL",
                include_posix,
                src,
                "-o",
                str(output),
            ],
            [
                "gcc",
                "-O3",
                "-dynamiclib",
                "-fPIC",
                "-DBUILDING_MODEL",
                include_posix,
                src,
                "-o",
                str(output),
            ],
        ]

    return [
        [
            "gcc",
            "-O3",
            "-shared",
            "-fPIC",
            "-DBUILDING_MODEL",
            include_posix,
            src,
            "-o",
            str(output),
        ],
        [
            "clang",
            "-O3",
            "-shared",
            "-fPIC",
            "-DBUILDING_MODEL",
            include_posix,
            src,
            "-o",
            str(output),
        ],
    ]



def _build_library() -> Path:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    output = BUILD_DIR / _shared_name()
    errors: list[str] = []
    for cmd in _candidate_commands(output):
        try:
            completed = subprocess.run(
                cmd,
                cwd=str(ROOT),
                check=True,
                capture_output=True,
                text=True,)
        except FileNotFoundError:
            errors.append("missing compiler: " + cmd[0])
            continue
        except subprocess.CalledProcessError as exc:
            message = exc.stderr or exc.stdout or str(exc)
            errors.append(message.strip())
            continue
        BUILD_METADATA.clear()
        BUILD_METADATA.update(
            {"compiler": cmd[0],
                "flags": cmd[1:],
                "command": cmd,
                "library": str(output),})
        if completed.stdout:
            BUILD_METADATA["stdout"] = completed.stdout.strip()
        if completed.stderr:
            BUILD_METADATA["stderr"] = completed.stderr.strip()
        return output
    raise RuntimeError("; ".join(errors) if errors else "no compiler available")  # WRITTEN BY AI


def _hash_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def model_source_hash() -> str:
    """Computes the SHA-256 hash of the C model source file.

    This is used to verify the integrity of the compiled model and ensure reproducibility.

    Returns:
        str: The hexadecimal SHA-256 hash digest of the `model.c` file.

    Note:
        Documentation generated by Jules (Google AI).
    """
    return _hash_file(SRC_DIR / "model.c")


def _load_library() -> Optional[ctypes.CDLL]:
    lib_path = BUILD_DIR / _shared_name()
    if lib_path.exists():
        try:
            lib = ctypes.CDLL(str(lib_path))
            BUILD_METADATA.setdefault("library", str(lib_path))
            return lib
        except OSError:
            pass
    try:
        lib_path = _build_library()
    except RuntimeError as exc:
        raise RuntimeError(f"Failed to build C backend: {exc}") from exc  # WRITTEN BY AI
    lib = ctypes.CDLL(str(lib_path))
    return lib


class BergmanParams(Structure):
    """CTypes structure mapping to the C `BergmanParams` struct.

    This structure holds the physiological parameters required by the Bergman minimal model.

    Attributes:
        S_G (c_double): Glucose effectiveness (min^-1).
        p2 (c_double): Rate of decrease of tissue glucose uptake ability (min^-1).
        p3 (c_double): Rate of increase of tissue glucose uptake ability (min^-1 per uU/mL).
        n (c_double): Insulin clearance rate (min^-1).
        Gb (c_double): Basal glucose concentration (mg/dL).
        Ib (c_double): Basal insulin concentration (uU/mL).

    Note:
        Documentation generated by Jules (Google AI).
    """
    _fields_ = [
        ("S_G", c_double),
        ("p2", c_double),
        ("p3", c_double),
        ("n", c_double),
        ("Gb", c_double),
        ("Ib", c_double),
    ]


lib: Optional[ctypes.CDLL] = _load_library()

if lib is not None:
    lib.set_params.argtypes = [BergmanParams]
    lib.set_params.restype = None
    lib.step.argtypes = [
        POINTER(c_double),
        POINTER(c_double),
        POINTER(c_double),
        c_double,
        c_double,
        c_double,
        c_double,
        c_double,
    ]
    lib.step.restype = None


def set_params_from_dict(params: Dict[str, float]) -> None:
    """Sets the parameters of the underlying C model from a dictionary.

    This function converts the dictionary parameters into a `BergmanParams` C structure
    and passes it to the loaded C library.

    Args:
        params (Dict[str, float]): A dictionary containing the model parameters.
            Expected keys are:
            - "S_G_min1"
            - "p2_min1"
            - "p3_min1_per_uU_mL"
            - "n_min1"
            - "Gb_mg_dL"
            - "Ib_uU_mL"

    Raises:
        RuntimeError: If the C library is not loaded.

    Note:
        Documentation generated by Jules (Google AI).
    """
    if lib is None:
        raise RuntimeError("C library not loaded; cannot set parameters")  # WRITTEN BY AI
    bp = BergmanParams(
        float(params["S_G_min1"]),
        float(params["p2_min1"]),
        float(params["p3_min1_per_uU_mL"]),
        float(params["n_min1"]),
        float(params["Gb_mg_dL"]),
        float(params["Ib_uU_mL"]),
    )
    lib.set_params(bp)


def get_build_metadata() -> Dict[str, object]:
    """Retrieves metadata about the C model build environment.

    This includes information about the compiler used, flags, the command executed,
    the library path, the source file hash, and the system environment.

    Returns:
        Dict[str, object]: A dictionary containing build metadata.

    Note:
        Documentation generated by Jules (Google AI).
    """
    metadata = dict(BUILD_METADATA)
    metadata.setdefault("library", str(BUILD_DIR / _shared_name()))
    metadata.setdefault("compiler", None)
    metadata.setdefault("flags", [])
    metadata.setdefault("command", [])
    metadata["source_hash"] = model_source_hash()
    metadata["platform"] = platform.platform()
    metadata["python"] = sys.version
    return metadata
