#ifndef MODEL_H
#define MODEL_H

#ifdef _WIN32
  #ifdef BUILDING_MODEL
    #define EXPORT __declspec(dllexport)
  #else
    #define EXPORT __declspec(dllimport)
  #endif
#else
  #define EXPORT __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Structure holding the physiological parameters for the Bergman minimal model.
 *
 * @note Documentation generated by Jules (Google AI).
 */
typedef struct {
    double S_G; /**< Glucose effectiveness (min^-1). */
    double p2;  /**< Rate of decrease of tissue glucose uptake ability (min^-1). */
    double p3;  /**< Rate of increase of tissue glucose uptake ability (min^-1 per uU/mL). */
    double n;   /**< Insulin clearance rate (min^-1). */
    double Gb;  /**< Basal glucose concentration (mg/dL). */
    double Ib;  /**< Basal insulin concentration (uU/mL). */
} BergmanParams;

/**
 * @brief Sets the global parameters for the Bergman minimal model.
 *
 * @param p The structure containing the parameters to set.
 *
 * @note Documentation generated by Jules (Google AI).
 */
EXPORT void set_params(BergmanParams p);

/**
 * @brief Performs a single time step of the simulation using the Runge-Kutta 4 method.
 *
 * @param G Pointer to the current glucose concentration (mg/dL). Updated in place.
 * @param X Pointer to the current remote insulin effect (min^-1). Updated in place.
 * @param I Pointer to the current insulin concentration (uU/mL). Updated in place.
 * @param Gb Basal glucose concentration (mg/dL).
 * @param Ib Basal insulin concentration (uU/mL).
 * @param dt Time step size (min).
 * @param D Rate of glucose appearance from the gut (mg/dL/min).
 * @param u Insulin secretion stimulus (uU/mL/min).
 *
 * @note Documentation generated by Jules (Google AI).
 */
EXPORT void step(double* G, double* X, double* I,
                 double Gb, double Ib,
                 double dt, double D, double u);

#ifdef __cplusplus
}
#endif

#endif /* MODEL_H */
