/* RK4 integrator for the Bergman minimal model, bridged via ctypes. */
#include "model.h"

#include <math.h>

static double S_G_ = 0.0;
static double p2_  = 0.0;
static double p3_  = 0.0;
static double n_   = 0.0;
static double Gb_  = 0.0;
static double Ib_  = 0.0;

/**
 * @brief Sets the global parameters for the Bergman minimal model.
 *
 * This function updates the internal static variables used by the `step` function.
 *
 * @param p The structure containing the parameters to set.
 *
 * @note Documentation generated by Jules (Google AI).
 */
EXPORT void set_params(BergmanParams p) {
    S_G_ = p.S_G;
    p2_  = p.p2;
    p3_  = p.p3;
    n_   = p.n;
    Gb_  = p.Gb;
    Ib_  = p.Ib;
}

static void compute_derivatives(double G, double X, double I,
                                double D, double u,
                                double* dG, double* dX, double* dI) {
    *dG = -(S_G_ + X) * (G - Gb_) + D;
    *dX = -p2_ * X + p3_ * (I - Ib_);
    *dI = -n_  * (I - Ib_) + u;
}

/**
 * @brief Performs a single time step of the simulation using the Runge-Kutta 4 method.
 *
 * This function integrates the Bergman minimal model differential equations over
 * a single time step `dt`. It updates the state variables G, X, and I in place.
 *
 * The equations solved are:
 * dG/dt = -(S_G + X)(G - Gb) + D(t)
 * dX/dt = -p2*X + p3*(I - Ib)
 * dI/dt = -n*(I - Ib) + u(t)
 *
 * @param G Pointer to the current glucose concentration (mg/dL). Updated in place.
 * @param X Pointer to the current remote insulin effect (min^-1). Updated in place.
 * @param I Pointer to the current insulin concentration (uU/mL). Updated in place.
 * @param Gb Basal glucose concentration (mg/dL).
 * @param Ib Basal insulin concentration (uU/mL).
 * @param dt Time step size (min).
 * @param D Rate of glucose appearance from the gut (mg/dL/min).
 * @param u Insulin secretion stimulus (uU/mL/min).
 *
 * @note Documentation generated by Jules (Google AI).
 */
EXPORT void step(double* G, double* X, double* I,
                 double Gb, double Ib,
                 double dt, double D, double u) {
    (void)Gb;
    (void)Ib;

    double g = *G;
    double x = *X;
    double ins = *I;

    double k1_g, k1_x, k1_i;
    double k2_g, k2_x, k2_i;
    double k3_g, k3_x, k3_i;
    double k4_g, k4_x, k4_i;

    double dG, dX, dI;

    compute_derivatives(g, x, ins, D, u, &dG, &dX, &dI);
    k1_g = dt * dG;
    k1_x = dt * dX;
    k1_i = dt * dI;

    compute_derivatives(g + 0.5 * k1_g, x + 0.5 * k1_x, ins + 0.5 * k1_i,
                        D, u, &dG, &dX, &dI);
    k2_g = dt * dG;
    k2_x = dt * dX;
    k2_i = dt * dI;

    compute_derivatives(g + 0.5 * k2_g, x + 0.5 * k2_x, ins + 0.5 * k2_i,
                        D, u, &dG, &dX, &dI);
    k3_g = dt * dG;
    k3_x = dt * dX;
    k3_i = dt * dI;

    compute_derivatives(g + k3_g, x + k3_x, ins + k3_i,
                        D, u, &dG, &dX, &dI);
    k4_g = dt * dG;
    k4_x = dt * dX;
    k4_i = dt * dI;

    g   += (k1_g + 2.0 * k2_g + 2.0 * k3_g + k4_g) / 6.0;
    x   += (k1_x + 2.0 * k2_x + 2.0 * k3_x + k4_x) / 6.0;
    ins += (k1_i + 2.0 * k2_i + 2.0 * k3_i + k4_i) / 6.0;

    *G = g;
    *X = x;
    *I = ins;
}
